receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  # <- changed from localhost
      http:
        endpoint: 0.0.0.0:4318  # <- changed from localhost

exporters:
  debug:
    verbosity: detailed

  otlp/elastic:
    endpoint: "APM Endpoint url:443"
    headers:
      Authorization: "Bearer secret token"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]

    metrics:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]

    logs:  
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
